language: r
cache: packages
sudo: required

before_install:
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
    - sudo apt-get --yes --force-yes update -qq
    - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev
    - # install gdal from source
    - chmod +x .travis_install_gdal-2.3.sh && ./.travis_install_gdal-2.3.sh
    - # use c++11 for package compilation
    - chmod +x .travis_change_R_compiler.sh && ./.travis_change_R_compiler.sh


script:
  - Rscript R/run_all_data_analysis_scripts.R  
