language: r
cache: packages
sudo: required

before_install:
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
    - sudo apt-get --yes --force-yes update -qq
    - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev
    - # install gdal from source
    - wget http://download.osgeo.org/gdal/2.3.1/gdal-2.3.1.tar.gz 
    - tar -xzf gdal-2.3.1.tar.gz 
    - cd gdal-2.3.1
    - ./configure
    - make
    - sudo make install
    - cd ..

script:
  - Rscript R/run_all_data_analysis_scripts.R  
